### ISSUE TITLE
Exception while selecting generation scheme from download subfolder menu with more than five custom presets

### ISSUE THREAD

**Issue by luficer** [damonlynch/rapid-photo-downloader#85] opened 2022-08-08 20:50 UTC
I am unable to access Photo settings in destination tab; when I press the cog wheel I get error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/raphodo/ui/destinationdisplay.py", line 734, in mousePressEvent
    self.setupMenuActions()
  File "/usr/lib/python3/dist-packages/raphodo/ui/destinationdisplay.py", line 423, in setupMenuActions
    action = self.map_action[index]  # type: QAction
KeyError: 11

RPD v0.9.33
Running on Ubuntu 22.04

Please advise, 
Thank you

[rpd-bug-report-20220808.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/9284968/rpd-bug-report-20220808.tar.gz)

**Comment by luficer** [comment] 2022-08-08 20:57
RPD v0.9.33
Running on Ubuntu 22.04

**Comment by damonlynch** [comment] 2022-08-09 10:33
Thanks for your bug report. I have confirmed the bug. Unfortunately I cannot fix it at this time due to a hand injury I picked up while working on the program earlier this year. I am dictating this message using a voice recognition program. 

If you want to use the program in the meantime, replace the file `/home/koi/.config/Rapid Photo Downloader/Rapid Photo Downloader.conf` with the unzipped attached version. The last custom preset you generated is no longer present in it. To avoid replicating the bug, as long as you have more than six custom presets (which you do), save any new preset you create before closing the preset editor.

[Rapid Photo Downloader.conf.zip](https://github.com/damonlynch/rapid-photo-downloader/files/9289613/Rapid.Photo.Downloader.conf.zip)
.

**Closed** 2023-12-26 04:08 UTC
Labels: bug
