### ISSUE TITLE
Problems with python at rpd opening

### ISSUE THREAD

**Issue by luckyboy94120** [damonlynch/rapid-photo-downloader#124] opened 2024-02-12 15:02 UTC
[rpd-bug-report-20240212.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14239865/rpd-bug-report-20240212.tar.gz)
Hi guys!

I have this problem at rapid-photo-downloader opening, can you help me please?

`Traceback (most recent call last):
  File "/usr/bin/rapid-photo-downloader", line 33, in <module>
    sys.exit(load_entry_point('rapid-photo-downloader==0.9.34', 'gui_scripts', 'rapid-photo-downloader')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/rapid.py", line 7877, in main
    rw = RapidWindow(
         ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/rapid.py", line 561, in __init__
    self.prefs.check_show_system_folders()
  File "/usr/lib/python3.11/site-packages/raphodo/prefs/preferences.py", line 1173, in check_show_system_folders
    if self.source_or_destination_is_system_folder():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/prefs/preferences.py", line 1187, in source_or_destination_is_system_folder
    if get_media_dir().startswith("/run"):
       ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/storage/storage.py", line 272, in get_media_dir
    distro = get_distro()
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/storage/storage.py", line 164, in get_distro
    os_release = parse_os_release()
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/storage/storage.py", line 149, in parse_os_release
    k, v = line.split("=", maxsplit=1)
    ^^^^
ValueError: not enough values to unpack (expected 2, got 1)
`
thanks

**Comment by damonlynch** [comment] 2024-02-12 20:15
You are running openSUSE Tumbleweed?

See https://github.com/damonlynch/rapid-photo-downloader/issues/122

**Comment by damonlynch** [comment] 2024-02-13 04:41
Marking as duplicate of #122. Let me know if it is not.

**Closed by damonlynch** 2024-02-13 04:41 UTC
Labels: needs information :raising_hand:
