### ISSUE TITLE
DL from CF-card extremely slow - RPD unuseable

### ISSUE THREAD

**Issue by che-rusker** [damonlynch/rapid-photo-downloader#199] opened 2024-04-15 14:39 UTC
Downloading 24 CR2-files from a Sandisk CF 60 MB/s UDMA takes way too long - see scrot. The app is not useable.
DL from internal device (SMB-share) is ok.

Linux Mint / RPD 0.9.36

![scrot_2024-03-29-	_Auswahl_001](https://github.com/damonlynch/rapid-photo-downloader/assets/67553563/26bf6ddd-b0cf-4f68-bbc3-8b43dff4d103)

**Comment by damonlynch** [comment] 2024-04-15 20:39
You are downloading to an SMB share, yes?

**Comment by che-rusker** [comment] 2024-04-16 09:02
> You are downloading to an SMB share, yes?

No, directly to a local SSD. 

I only download Smartphone-shots FROM a SMB-Share, as they are uploaded to my server via WiFi. But these are not the problem.

**Comment by damonlynch** [comment] 2024-04-16 09:07
I need a lot more information than a screenshot, which provides zero diagnostic data. Follow the instructions here: https://damonlynch.net/rapid/documentation/#reportproblem

**Comment by che-rusker** [comment] 2024-04-16 09:30
> I need a lot more information than a screenshot, which provides zero diagnostic data. Follow the instructions here: https://damonlynch.net/rapid/documentation/#reportproblem

Here you are...

[rpd-bug-report-20240416-1.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14994738/rpd-bug-report-20240416-1.tar.gz)

**Comment by damonlynch** [comment] 2024-04-16 10:31
The log files indicate no errors. The issue you are seeing is almost certainly caused by something external to Rapid Photo Downloader, which I have seen in the past with other users.  You can easily test this yourself by trying to copy files from the memory card using the command line, and seeing the speed. You can also use a benchmark utility.

You should also be sure to benchmark write performance to `/mnt/medien`. I don't know what that destination is, but that could also cause issues. 

It is one of the two that is slow — either the source, or the destination.

**Comment by che-rusker** [comment] 2024-04-16 10:56
> The log files indicate no errors. The issue you are seeing is almost certainly caused by something external to Rapid Photo Downloader, which I have seen in the past with other users. You can easily test this yourself by trying to copy files from the memory card using the command line, and seeing the speed. You can also use a benchmark utility.
> 
> You should also be sure to benchmark write performance to `/mnt/medien`. I don't know what that destination is, but that could also cause issues.
> 
> It is one of the two that is slow — either the source, or the destination.

The log is empty of course as I followed the advice from [here](https://damonlynch.net/rapid/documentation/#reportproblem) to make a fresh install of the latest version beforehand.
Darktable is able to DL all the files without problems. 
Plain copying works well too.
/mnt/medien is just a mountpoint for a BTRFS-formatted SSD.

There is no "external" cause.

**Comment by damonlynch** [comment] 2024-04-16 18:23
Did you run the benchmarks?

**Comment by damonlynch** [comment] 2024-04-17 00:08
I will close this issue unless read and write benchmarks are supplied. Currently zero diagnostic information has been supplied to narrow down the issue.

**Comment by che-rusker** [comment] 2024-04-17 13:33
So, here are the benchmarks...
![Bildschirmfoto vom 2024-04-17 15-29-40](https://github.com/damonlynch/rapid-photo-downloader/assets/67553563/3e281a27-bebb-49a8-8be0-4292ebb960c4)
![Bildschirmfoto vom 2024-04-17 15-27-01](https://github.com/damonlynch/rapid-photo-downloader/assets/67553563/2c2caf0a-e8f3-47f2-8f91-d658ef36765c)

Not all that bad.

**Comment by damonlynch** [comment] 2024-04-17 21:52
You confirm that is with the exact same memory card with which you saw the original issue? Not the same model, but the identical memory card?

**Comment by che-rusker** [comment] 2024-04-18 15:06
Yes.

**Comment by damonlynch** [comment] 2024-04-18 19:23
A good bug report **narrows down the cause of the problem** and **provides diagnostic information** to help solve it. To do that, here's what you need to do:

1. restart the computer
2. take one memory card that has at least a gigabyte of photos on it (CR2 files are fine)
3. configure Rapid Photo Downloader to download to your home directory (**very important: do not download to an external drive**)
4. make a note of the date and time
5. initiate the download to home directory in Rapid Photo Downloader
6. observe the performance
7. if the files are being copied slowly, again run a benchmark with the card as it is exactly (do not remove the card from the memory card in the meantime).
8. again assuming the files were being copied slowly, collect diagnostic information: run top to observe CPU usage, examine the kernel logs for any I/O issues, and use the program's main menu to generate a tar.gz with the log files.

Also, understand that I am in a different time zone from you. That means my waking hours are very different from yours.

**Comment by che-rusker** [comment] 2024-04-19 16:33
Sorry, but no. I got other things to do.
Also I had (of course) already tried to change the destination to a different drive - although the one that seems to be suspicious to you, is as internal as the one with /home. It makes no difference at all. 
For the record: There has never been any external drive or network-drive involved.

As I mentioned before: Darktable has no problem importing the very same photos from the very same CF-card. Nor has the excellent XnViewMP, BTW.
That is good enough for me. I am fine with that.
Also, understand that I clearly dislike your constantly condescending tone - whatever goes wrong, must be the stupid user's fault; it has nothing to do with your brilliant RPD... 

So long, and thanks for all the fish!

**Closed** 2024-04-19 20:07 UTC
Labels: needs information :raising_hand:
