### ISSUE TITLE
Files with unique identifier added via error handling are not marked as downloaded

### ISSUE THREAD

**Issue by tekaeren** [damonlynch/rapid-photo-downloader#33] opened 2021-08-24 13:17 UTC
Enable `Add unique identifier` in Preferences->Error Handling, and download files that will otherwise have same filenames after rename.
The files that would have identifier added in process, would not be marked as downloaded.

**Comment by damonlynch** [comment] 2021-08-24 17:09
I cannot reproduce this. You need to provide me with more information. 

1. Create a test folder to download from, and in that test folder, create three subfolders.
2. In each of those three subfolders, copy the exact same file.
3. Set the download source to be the test folder
4. Start the download and when it finishes open the Error Reports window. Then create a screenshot of the Rapid Photo Downloader main window and the Error Reports windows so that both are showing, and attach it here. I have attached a sample to illustrate what I want.

![Screenshot from 2021-08-24 13-07-21](https://user-images.githubusercontent.com/1749868/130659862-7ae8255c-1088-488e-8fcf-c3f5a57d79a1.png)

**Comment by tekaeren** [comment] 2021-09-16 11:54
I've missed the notification...
My workflow is as follows:
1. create pictures, that will fall under `add unique identifier` (ie. by cloning, or burst shots)
2. select all files for download
2a. all files are downloaded - not overlapping have green sign, those with added unique id have yellow one (with hint that uID has been added)
3. change source dir - RPD asks if to clean the downloaded files from view - click yes
4. get back to dir with test files - the files that have been downloaded without unique id(with green signs), are unselected and greyed out; the files with unique id (with yellow signs) are marked for download as if never had been downloaded
4a - if `show` filter is changed from all -> new, only the files with unique id are visible 
5. Downloading the files again will create copies with unique ids of the following numbers to previous download.

Repeating the steps will download the files with automatically added unique ids, each time iterating the id and creating copies.

![7](https://user-images.githubusercontent.com/46860959/133607451-28d2f78a-d7a0-4997-a6e0-265f96e6e725.png)
![6](https://user-images.githubusercontent.com/46860959/133607459-e18f2e5f-19ca-42de-8a5c-05cfd17953a2.png)
![5](https://user-images.githubusercontent.com/46860959/133607464-f5950f22-ac6d-4585-8290-6a213b1565e8.png)
![4](https://user-images.githubusercontent.com/46860959/133607468-ae7b6254-ea39-4c27-9774-d6785b75ec71.png)
![3](https://user-images.githubusercontent.com/46860959/133607473-a549f0d2-7eca-4338-8535-3210d8c9fe7d.png)
![2](https://user-images.githubusercontent.com/46860959/133607476-e9a676e6-9bc2-4f50-a1fb-31da8d9a9a1f.png)
![1](https://user-images.githubusercontent.com/46860959/133607480-40e39f94-056f-4e32-8069-93fa41fae160.png)

**Comment by damonlynch** [comment] 2021-09-19 17:48
The program is behaving as expected. There is no bug. When a file is downloaded or fails to download, the program's default behaviour is to display its icon in the user interface, _irrespective of what other download sources are added_. This is extremely important In situations when there are multiple copies of the same source photograph, e.g. cameras that write to two memory card simultaneously. The photographer needs to know what they have downloaded and what is available.

This however can be confusing when you see the same photo displayed in two separate thumbnails — one for the completed download, and one for the download that could happen again. But I don't see a way around this.

When you go back to the same directory you just downloaded from, the program is correctly displaying that the files have previously been downloaded. If you mark them for download, and download them again, of course, they will be downloaded again. But by default they are not marked for download.

I'm closing this for now. Please reopen it if you believe I have missed something and you believe have found a bug.

**Comment by tekaeren** [comment] 2021-09-21 11:54
If the files have not been marked for download automatically all would be great.
But from what I see, when I reenter the dir I've downloaded from files, the files that have been renamed with auto unique id are marked to download again. 
See the second image from the bottom of previous post, and the current (new screenshot made from the dir I've downloaded 5days ago
![Screenshot from 2021-09-21 13-50-04](https://user-images.githubusercontent.com/46860959/134165932-f2054985-fac1-4e6a-b037-9297369db44d.png)
).

**Comment by damonlynch** [comment] 2021-09-21 12:48
Please follow the instructions [here](https://damonlynch.net/rapid/documentation/#reportproblem) on how to create a tar file with the program configuration and log files. Then attach the tar file here. The program should be configured the same as it was when you made the screenshots.

**Comment by tekaeren** [comment] 2021-09-21 13:08
Support package attached.
[rpd-bug-report-20210921.zip](https://github.com/damonlynch/rapid-photo-downloader/files/7203268/rpd-bug-report-20210921.zip)

**Comment by tekaeren** [comment] 2021-10-01 09:14
> Thanks! I'm looking into it now. I'm curious, however, as to why you don't use sequence numbers in your filename generation. What makes you not want to use them? I am genuinely curious. I'd like to know so I can better design the program and/or documentation to better encourage their use.

I think this is because of habit... I've always used sequence numbers only for the photo sequences (like HDR, sport series, macro-depth, etc.) only. So it would "break" existing library.
On the second hand I'll need to check if sequence numbers in filename will not suffer from same problem.

I'm attaching the sqlite D
[downloaded_files.zip](https://github.com/damonlynch/rapid-photo-downloader/files/7265752/downloaded_files.zip)
B.

**Comment by damonlynch** [comment] 2021-10-01 21:26
> I think this is because of habit... I've always used sequence numbers only for the photo sequences (like HDR, sport series, macro-depth, etc.) only. So it would "break" existing library.
Personally I think you need to rethink your renaming strategy &mdash; if your camera can take more than one photo per second, a naming scheme that relies on HHMMSS to make a file unique is already broken.

I was finally able to replicate the bug. Fortunately the fix is a one line fix. Thanks for reporting it.

**Closed** 2021-10-01 21:29 UTC
Labels: bug
