### ISSUE TITLE
Fujifilm X-S20 Scan fails

### ISSUE THREAD

**Issue by drahcir2812** [damonlynch/rapid-photo-downloader#241] opened 2024-12-28 11:07 UTC
Scanning and loading pictures from the camera had already worked perfectly but recently always fails.
I start rapid-photo-download and then connect the camera using USB-C. After 1-3s the camera is identified correctly and scanning starts. It looks as if everything works well and the scanning nearly can complete successfully because the thumbnail pictures are already shown but then a failure window opens and informs that there was a problem and proposes to use the cameras memory card directly. Fortunately this works. Nevertheless I would prefer using the USB connection which is quick enough and more convenient for me.
I am using Linux Mint 22 Cinnamon (Version 6.2.9)
Linux-Kernel 6.8.0-51-generic
[rpd-bug-report-20241228.tar.gz](https://github.com/user-attachments/files/18265943/rpd-bug-report-20241228.tar.gz)

**Comment by damonlynch** [comment] 2024-12-28 20:29
Thanks for your bug report. This is a duplicate of #239. If you can, please follow the instructions in my response to that report.

**Closed by damonlynch** 2024-12-28 20:29 UTC
