### ISSUE TITLE
Wifi Flashair cards

### ISSUE THREAD

**Issue by freewee** [damonlynch/rapid-photo-downloader#35] opened 2021-09-26 13:09 UTC
Hi
Thank you for this beautiful soft!
But I get problems with my Wifi Toshiba Flashair cards.
The 03 and 04 versions of theses Flashair cards allow the card to be read in Ubuntu as drives, and this is nearly instantaneous.
But with RPD in Ubuntu 20.04, it takes several minutes for opening the folder, and creating 1 or 2 thumbnail, then hang...And becomes impossible to shut down, even with the system monitor!
I saw an error regarding a file (.CRW), but I tried to transfer the contents of my card in a folder on my PC, and RPD has no problem for managing this file.
So RPD seems to have a problem with DAV protocol?
I try 0.9.27a2 and it is the same.
In Ubuntu 18.04, it is a little bit better, but the time for creating thumbnails is very very long! But when the thumbnails are created, the transfer of the photos is very fast...
Thank you
[3rpd-bug-report-20210926-2.zip](https://github.com/damonlynch/rapid-photo-downloader/files/7231420/3rpd-bug-report-20210926-2.zip)

**Comment by damonlynch** [comment] 2021-09-26 13:39
Hi,

Thanks for your bug report. I'm sorry but I need to close this bug as "won't fix" because the problem is not in Rapid Photo Downloader itself. The problem is with the driver that controls the Wifi card. Rapid Photo Downloader uses simple Python copy commands to copy files; Python in turn uses standard Linux commands to copy files. If these commands are failing, that indicates a problem with the hardware driver. The same thing has occurred when other users have attempted to copy from a source or to a destination over ta network. If they don't configure their network correctly, failures result. They might not notice these failures until they run Rapid Photo Downloader, because Rapid Photo Downloader attempts to copy a lot of files very quickly.

If you want to continue to use Rapid Photo Downloader with this card, then probably the best solution is to copy the files to a folder on your computer using a program that does work (e..g Gnome Files), and the import that folder using Rapid Photo Downloader.

**Closed by damonlynch** 2021-09-26 13:39 UTC
