### ISSUE TITLE
Popups unreadable

### ISSUE THREAD

**Issue by Roebie** [damonlynch/rapid-photo-downloader#113] opened 2023-09-16 08:46 UTC
All popups in the application are unreadable as they are white text on a soft yellow background. Is there something I can do to change their appearance?
I'm using the latest version of Linux Mint and the latest version of RPD.
Thanks for all suggestions
![Screenshot from 2023-09-16 11-46-41](https://github.com/damonlynch/rapid-photo-downloader/assets/2420046/ae4ad74f-ce17-4c88-a402-e1d7b9b25e4e)

**Comment by damonlynch** [comment] 2023-09-16 20:09
This is a bug in Linux Mint. I strongly urge you to report the bug in the Linux Mint bug tracking system, otherwise it will not be fixed in the distribution itself.

Duplicate of #109. See that bug report for details how to fix the problem.

**Closed by damonlynch** 2023-09-16 20:09 UTC
