### ISSUE TITLE
Handle cameras that nest dual card slots in subfolders like the Fujifilm X-T3

### ISSUE THREAD

**Issue by wapitifass** [damonlynch/rapid-photo-downloader#59] opened 2022-02-04 08:49 UTC
- plugged in a camera (Fujifilm xt-3)
- turned it on
- opened rpd

**expected behaviour**

- rpd shows images from camera

**what actually happende**

- rpd shows the camera in the left
- I can't click it nor it loads the images

[rpd-bug-report-20220204.zip](https://github.com/damonlynch/rapid-photo-downloader/files/8001341/rpd-bug-report-20220204.zip)

**Comment by damonlynch** [comment] 2022-02-04 12:15
Discussion for this bug is happening at https://discuss.pixls.us/t/rpd-cant-import-images-directly-from-camera/29266

**Comment by damonlynch** [comment] 2022-02-28 00:47
Hi @wapitifass can you please do something important for me?:

1. Install `gphoto2` (a command line program)
2. Eject any memory cards 
3. plug in in your Fuji, 
4. ensure the camera is ejected from Nautilus or any other program that might automatically access it
5. run this from the command line, and copy and past the output here:

```
gphoto2 --list-folders
```

Here is a sample from my camera:

```
$ gphoto2 --list-folders
There is 1 folder in folder '/'.                                               
 - store_00020001
There are 2 folders in folder '/store_00020001'.
 - DCIM
 - MISC
There is 1 folder in folder '/store_00020001/DCIM'.
 - 100EOS1D
There are 0 folders in folder '/store_00020001/DCIM/100EOS1D'.
There are 0 folders in folder '/store_00020001/MISC'.
```

If you can do this within the next day I can include a fix for it in 0.9.30, which I hope will go into Ubuntu 22.04 (which means it will be in the Ubuntu repositories for the next 5 years).

**Comment by wapitifass** [comment] 2022-02-28 12:44
Hi @damonlynch ,

hope that helps.

```
Es gibt 1 Verzeichnis im Verzeichnis »/«.                                      
 - store_10000001
Es gibt 2 Verzeichnisse im Verzeichnis »/store_10000001«.
 - SLOT 1
 - SLOT 2
Es gibt 1 Verzeichnis im Verzeichnis »/store_10000001/SLOT 1«.
 - DCIM
Es gibt 1 Verzeichnis im Verzeichnis »/store_10000001/SLOT 1/DCIM«.
 - 100_FUJI
Es gibt 0 Verzeichnisse im Verzeichnis »/store_10000001/SLOT 1/DCIM/100_FUJI«.
Es gibt 1 Verzeichnis im Verzeichnis »/store_10000001/SLOT 2«.
 - DCIM
Es gibt 1 Verzeichnis im Verzeichnis »/store_10000001/SLOT 2/DCIM«.
 - 100_FUJI
Es gibt 0 Verzeichnisse im Verzeichnis »/store_10000001/SLOT 2/DCIM/100_FUJI«.
```

**Comment by damonlynch** [comment] 2022-02-28 22:14
@wapitifass can you please test the 0.9.30b1 release, which I made just now? I have no way of testing if it works or not with any of my cameras. To test, you need to remove SLOT1 and SLOT2 from the list of folders to scan in the program preferences. Unless these two values are removed, the new code will not be tested. Thanks.

**Comment by damonlynch** [comment] 2022-03-05 02:00
I'm marking this as closed for now. Please test and reopen if 0.9.30 does not resolve the problem.

**Comment by wapitifass** [comment] 2022-03-08 16:40
Hi, sorry for the late reply. Unfortunately it didn't work.
Here's the bugreport:

[rpd-bug-report-20220308.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/8208028/rpd-bug-report-20220308.tar.gz)

**Comment by damonlynch** [comment] 2022-03-08 16:47
It looks like the code I added worked as intended, but I did not anticipate the problem later in the scan process. This is a challenging problem to fix because I do not own one of these cameras. I will need to rely on your help for you to test the code before it is released. Can I rely on your help for this?

**Comment by wapitifass** [comment] 2022-03-08 16:50
Sure, I'll help wherever I can.

**Comment by damonlynch** [comment] 2022-03-10 16:26
@wapitifass please email me and I will email you an unreleased version of Rapid Photo Downloader to test with your camera. My email address is at the bottom of my [personal home page](https://damonlynch.net/).

**Closed** 2022-03-10 20:37 UTC
Labels: bug
